In [30]:
import numpy as np
import pandas as pd
from pathlib import Path

In [31]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'),true_values=['Y','y'],false_values=['N','n'])  #start cleaning by making Y and N's into true/false which are boolean and treatable as 1/0
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'),true_values=['Y','y'],false_values=['N','n'])

In [32]:
train_df.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'home_ownership', 'annual_inc', 'verification_status', 'loan_status',
       'pymnt_plan', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'policy_code', 'application_type',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'debt_settlement_flag'],
      dtype='object')

In [33]:
# Convert categorical data to numeric and separate target feature for training data
train_df = pd.get_dummies(train_df)
train_df.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,loan_status_high_risk,loan_status_low_risk,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App
0,57107,57107,13375.0,0.1797,483.34,223000.0,False,29.99,0.0,0.0,...,0,1,0,0,0,1,0,1,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,False,11.26,2.0,0.0,...,0,0,1,0,0,1,0,1,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,False,11.28,0.0,0.0,...,0,0,1,0,0,1,0,1,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,False,18.08,0.0,0.0,...,1,1,0,0,0,1,0,1,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,False,27.77,0.0,2.0,...,0,0,1,0,0,1,0,1,1,0
5,31295,31295,6500.0,0.1614,228.98,65000.0,False,27.49,1.0,0.0,...,0,1,0,0,0,1,0,1,1,0
6,173238,173238,40000.0,0.1240,897.89,171000.0,False,20.74,0.0,0.0,...,0,1,0,0,0,1,0,1,1,0
7,116755,116755,5000.0,0.1719,178.74,55000.0,False,10.80,1.0,0.0,...,0,1,0,0,0,1,0,1,1,0
8,170311,170311,6000.0,0.1102,196.49,36000.0,False,27.28,0.0,0.0,...,0,1,0,0,0,1,0,1,1,0
9,254794,254794,10625.0,0.1102,347.95,73000.0,False,7.09,0.0,2.0,...,1,0,1,0,0,1,0,1,1,0

In [34]:
# Convert categorical data to numeric and separate target feature for training data
test_df = pd.get_dummies(test_df)
test_df.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,loan_status_high_risk,loan_status_low_risk,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App
0,67991,67991,40000.0,0.0819,814.70,140000.0,False,19.75,0.0,1.0,...,0,1,0,0,0,1,0,1,1,0
1,25429,25429,6000.0,0.1524,208.70,55000.0,False,11.52,2.0,0.0,...,1,1,0,0,0,1,0,1,1,0
2,38496,38496,3600.0,0.1695,128.27,42000.0,False,6.74,0.0,0.0,...,1,1,0,0,0,1,0,1,1,0
3,19667,19667,20000.0,0.1524,478.33,100000.0,False,12.13,0.0,2.0,...,1,1,0,0,0,1,0,1,1,0
4,37505,37505,3600.0,0.1240,120.27,50000.0,False,16.08,0.0,3.0,...,1,1,0,0,0,1,0,1,1,0
5,26517,26517,27000.0,0.0819,549.93,57000.0,False,31.41,0.0,0.0,...,1,0,0,1,0,1,0,1,0,1
6,30063,30063,15000.0,0.0881,310.00,50000.0,False,24.44,0.0,1.0,...,0,1,0,0,0,1,0,1,1,0
7,31659,31659,19000.0,0.0881,602.52,70000.0,False,30.94,0.0,0.0,...,0,1,0,0,0,1,0,1,0,1
8,15003,15003,27575.0,0.1171,912.07,142000.0,False,17.90,0.0,0.0,...,0,0,1,0,0,1,0,1,1,0
9,75464,75464,31500.0,0.1774,795.45,100000.0,False,25.05,2.0,1.0,...,0,0,1,0,0,1,0,1,1,0

In [35]:
# add missing dummy variables to testing set
for col in train_df.columns:
    if col not in test_df.columns:
        test_df[col] = 0
test_df = test_df.applymap(lambda x: 0 if (not x) else x )
test_df.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,loan_status_high_risk,loan_status_low_risk,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App
0,67991,67991,40000.0,0.0819,814.70,140000.0,0,19.75,0.0,1.0,...,0,1,0,0,0,1,0,1,1,0
1,25429,25429,6000.0,0.1524,208.70,55000.0,0,11.52,2.0,0.0,...,1,1,0,0,0,1,0,1,1,0
2,38496,38496,3600.0,0.1695,128.27,42000.0,0,6.74,0.0,0.0,...,1,1,0,0,0,1,0,1,1,0
3,19667,19667,20000.0,0.1524,478.33,100000.0,0,12.13,0.0,2.0,...,1,1,0,0,0,1,0,1,1,0
4,37505,37505,3600.0,0.1240,120.27,50000.0,0,16.08,0.0,3.0,...,1,1,0,0,0,1,0,1,1,0
5,26517,26517,27000.0,0.0819,549.93,57000.0,0,31.41,0.0,0.0,...,1,0,0,1,0,1,0,1,0,1
6,30063,30063,15000.0,0.0881,310.00,50000.0,0,24.44,0.0,1.0,...,0,1,0,0,0,1,0,1,1,0
7,31659,31659,19000.0,0.0881,602.52,70000.0,0,30.94,0.0,0.0,...,0,1,0,0,0,1,0,1,0,1
8,15003,15003,27575.0,0.1171,912.07,142000.0,0,17.90,0.0,0.0,...,0,0,1,0,0,1,0,1,1,0
9,75464,75464,31500.0,0.1774,795.45,100000.0,0,25.05,2.0,1.0,...,0,0,1,0,0,1,0,1,1,0

In [36]:

X_test = test_df.drop('loan_status_high_risk', axis=1)
Y_test = test_df['loan_status_high_risk']
for col in X_test.columns:
    if 'loan_status' in col:
        X_test= X_test.drop(col, axis=1)
        test_df = test_df.drop(col, axis=1)

test_df

X_train = train_df.drop('loan_status_high_risk', axis=1)
Y_train = train_df['loan_status_high_risk']
for col in X_train.columns:
    if 'loan_status' in col:
        X_train= X_train.drop(col, axis=1)
        train_df = train_df.drop(col, axis=1)

## Create Classification models for the data

Logistic and random forrest models are going to be created to guess if a user has a high risk status of defaulting on a new loan.  The logistic classification is not going to be very accurate without standardizing the data since so many variables are in completely different ranges.  However standardizing the data should not have a large impact on random forest classification since it uses thresholds and binary choices.

Different data will yield different results and the RFC gives a 0.62 accuracy which is significantly better than guessing. which is good for advertizement however using it for something more like actual loan aproval it would probably require a higher accuracy to implement.

In [37]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter =10000)
classifier.fit(X_train,Y_train)
print(f"Training Data Score: {classifier.score(X_train,Y_train)}")
print(f"Testing Data Score: {classifier.score(X_test,Y_test)}")

Training Data Score: 0.6988505747126437
Testing Data Score: 0.5650786899191833

c:\Users\zzpie\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [62]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=1 ,max_leaf_nodes=3000, n_jobs=64)
classifier.fit(X_train,Y_train)
print(f"Training Data Score: {classifier.score(X_train,Y_train)}")
print(f"Testing Data Score: {classifier.score(X_test,Y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.6229264142917907

## Standardizing Data
after doing a non standardized test the data will be standardized using a standard scaler.  This is a mean deviation formula standardizing on a scale of varience.  This allows variables to be compared to each other without issues of scale, such as some variables may be on a scale of 0-1 and others might be in the tens or hundreds of thousands

In [39]:
# Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(train_df.drop('loan_status_high_risk', axis=1))
X_train_scaled = scaler.transform(train_df.drop('loan_status_high_risk', axis=1))
X_test_scaled = scaler.transform(test_df.drop('loan_status_high_risk', axis=1))

#### models after scaling

after we scale we will see a dramatic increase in accuracy from the logistic model however the random forest will have very similar accuracy.


After applying we see a accuracy of about 0.72 with the logistic which is entering on an accuracy for professional use cases.

THe random forest model does not noticable improve after scaling data. adjusting hyper params would be more useful than scaling data for models like random forest.

In [40]:
# Train the Logistic Regression model on the scaled data and print the model score
classifier = LogisticRegression(max_iter =10000)
classifier.fit(X_train_scaled,train_df['loan_status_high_risk'])
print(f"Training Data Score: {classifier.score(X_train_scaled,train_df['loan_status_high_risk'])}")
print(f"Testing Data Score: {classifier.score(X_test_scaled,test_df['loan_status_high_risk'])}")

Training Data Score: 0.7129720853858785
Testing Data Score: 0.7203317737133135

In [61]:
# Train a Random Forest Classifier model on the scaled data and print the model score
classifier = RandomForestClassifier(random_state=1 ,max_leaf_nodes=3000, n_jobs=64)
classifier.fit(X_train_scaled,train_df['loan_status_high_risk'])
print(f"Training Data Score: {classifier.score(X_train_scaled,train_df['loan_status_high_risk'])}")
print(f"Testing Data Score: {classifier.score(X_test_scaled,test_df['loan_status_high_risk'])}")

Training Data Score: 1.0
Testing Data Score: 0.6216503615482774